# Generated by Django 4.2.2 on 2023-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='room',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='persons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
