# Generated by Django 4.2.2 on 2023-06-17 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_room_persons_remove_room_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_from', models.DateField()),
                ('date_till', models.DateField()),
                ('cost', models.IntegerField()),
                ('rooms', models.ManyToManyField(to='visitors.room')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
    ]
