# Generated by Django 4.2.2 on 2023-06-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_from',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_till',
            new_name='check_out',
        ),
    ]
