# Generated by Django 4.2.2 on 2023-06-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_user_current_booking_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_booking_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_booking_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
