# Generated by Django 4.2.2 on 2023-06-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_user_current_booking_in_user_current_booking_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
