# Generated by Django 4.2.2 on 2023-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_alter_booking_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
